meta_product_name: "ChefsYa"
meta_title: "ChefsYa - Los mejores chefs de tu zona, cocinando en tu casa"
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
